development:
  adapter: sqlite3
  encoding: utf8
  reconnect: false
  database: db/ps_development.sqlite3
test:
  adapter: sqlite3
  encoding: utf8
  reconnect: false
  database: db/ps_testing.sqlite3
